# Package make targets
VIP_AHB_EXAMPLE_ENV_PKG =\
+incdir+$(VIP_HOME)/questa_mvc_src/sv \
+incdir+$(UVMF_VIP_LIBRARY_HOME)/environment_packages/vip_ahb_example_env_pkg \
$(UVMF_VIP_LIBRARY_HOME)/environment_packages/vip_ahb_example_env_pkg/vip_ahb_example_env_pkg.sv

comp_vip_ahb_env_pkg:
	$(HVL_COMP_CMD) $(VIP_AHB_EXAMPLE_ENV_PKG)

