# qvip_ethernet_parallel environment packages source and make target

qvip_ethernet_parallel_ENV_PKG =\
		 $(UVMF_VIP_LIBRARY_HOME)/environment_packages/qvip_ethernet_parallel_env_pkg/qvip_ethernet_parallel_env_pkg.sv

comp_qvip_ethernet_parallel_env_pkg:
		$(HVL_COMP_CMD) +incdir+$(UVMF_VIP_LIBRARY_HOME)/environment_packages/qvip_ethernet_parallel_env_pkg $(qvip_ethernet_parallel_ENV_PKG)
