---
## To instantiate this subenv in a higher level, use this structure:
##  qvip_subenvs :
##    - { name: "<instance_name_of_subenv>", type: "axi4_2x2_fabric_qvip" }
uvmf:
  qvip_environments:
    "axi4_2x2_fabric_qvip":
      agents:
        - name: 'mgc_axi4_m0'
          active_passive: 'ACTIVE'
          initial_sequence: 'axi4_slave_sequence'
          ap_info :
            - port_name: "ap"
              key: "trans_ap"
              type: "axi4_master_rw_transaction#(<enter_parameters_here>)"
        - name: 'mgc_axi4_m1'
          active_passive: 'ACTIVE'
        - name: 'mgc_axi4_s0'
          active_passive: 'ACTIVE'
        - name: 'mgc_axi4_s1'
          active_passive: 'ACTIVE'
      imports:
        - { name: 'mgc_axi4_v1_0_pkg' }
...