# Package make targets
QVIP_AHB_EXAMPLE_ENV_PKG =\
+incdir+$(UVMF_VIP_LIBRARY_HOME)/environment_packages/qvip_ahb_example_env_pkg \
$(UVMF_VIP_LIBRARY_HOME)/environment_packages/qvip_ahb_example_env_pkg/qvip_ahb_example_env_pkg.sv 

comp_qvip_ahb_example_env_pkg:
	$(HVL_COMP_CMD) $(QVIP_AHB_EXAMPLE_ENV_PKG)

