# Package make targets
QVIP_USB3_PIPE_EXAMPLE_ENV_PKG =\
+incdir+$(UVMF_VIP_LIBRARY_HOME)/environment_packages/qvip_usb3_pipe_example_env_pkg \
$(UVMF_VIP_LIBRARY_HOME)/environment_packages/qvip_usb3_pipe_example_env_pkg/qvip_usb3_pipe_example_env_pkg.sv 

comp_qvip_usb3_pipe_example_env_pkg:
	$(HVL_COMP_CMD) $(QVIP_USB3_PIPE_EXAMPLE_ENV_PKG)

