# Package make targets
VIP_AXI3_AHB_ENV_PKG =\
+incdir+$(VIP_HOME)/questa_mvc_src/sv \
+incdir+$(UVMF_VIP_LIBRARY_HOME)/environment_packages/vip_axi3_ahb_env_pkg \
$(UVMF_VIP_LIBRARY_HOME)/environment_packages/vip_axi3_ahb_env_pkg/vip_axi3_ahb_env_pkg.sv

comp_vip_axi3_ahb_env_pkg:
	$(HVL_COMP_CMD) $(VIP_AXI3_AHB_ENV_PKG)

